### ISSUE TITLE
Family reference data for PMD4

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/pmd-jenkins-library#17]
Refactor https://github.com/GSS-Cogs/pmd-jenkins-library/blob/family-pmd4/vars/familyReferencePipeline.groovy for PMD4. Depends a bit on #15.

**Comment by robons** [comment]
@ajtucker I presume it'd be a good idea if we could get the regular ref common pipeline working off this as well?

**Comment by ajtucker** [comment]
Yes. Actually, the Jenkinsfile for ref_common targeting PMD4 is in a separate branch: https://github.com/GSS-Cogs/ref_common/blob/pmd4/Jenkinsfile

**Comment by robons** [comment]
Update from @ajtucker, Need to include the columns.csv and components.csv (and upload to PMD) so that we can create dimensions at the family level.

**Comment by robons** [comment]
The changes in the PR are now ready for review.
