### ISSUE TITLE
pmd-jenkins-library: Look for csv gz as well as csv (family-pmd4 branch)

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/pmd-jenkins-library#23]
Currently the family-pmd4 branch only looks for input files ending .csv, we need to update it to also look for .csv.gz.

probably this line: https://github.com/GSS-Cogs/pmd-jenkins-library/blob/2c016fa0f888570db9dae2bbc475eb3c8a193dc1/vars/familyTransformPipeline.groovy#L95

**Comment by ajtucker** [comment]
It's merged, but not fully tested. Happy to close this and we'll see how things work in practice.
