### ISSUE TITLE
Start Failing Build on SPARQL Test Failures

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/pmd-jenkins-library#37]
The test failures mean that we haven't got RDF which matched up with what PMD requires. After completing #36 we should start passing tests. So after that point, if a build fails a SPARQL test, we need to start failing the build (and avoiding publishing drafts to PMD).

**Comment by ajtucker** [comment]
The `-i` flag to sparql-test-runner causes the return code to be success (0) and so will need removing once we get to this: https://github.com/GSS-Cogs/pmd-jenkins-library/blob/family-pmd4/vars/familyTransformPipeline.groovy#L282

**Comment by robons** [comment]
So I've come across a bit of a stumbling block in a similar vain to https://github.com/GSS-Cogs/gss-utils/pull/134. Say we have the following column definitions:
```
             "Week": {
                "parent": "http://purl.org/linked-data/sdmx/2009/dimension#refPeriod",
                "value": "http://reference.data.gov.uk/id/{+week}"
            },
            "Area code": {
                "parent": "http://purl.org/linked-data/sdmx/2009/dimension#refArea",
                "value": "http://statistics.data.gov.uk/id/statistical-geography/{area_code}",
                "description": ""
            },
```

These are two definitions which we're using in a large number of places. 

For the reference.data.gov.uk URIs there is certainly no codelist which can be used to define all possible durations/points in times which are valid (and how you would represent these in a hierarchical codelist, who knows?). It should be noted, however that the qb specification says that associating a qb:codeList with a dimension is (technically) [optional](https://www.w3.org/TR/vocab-data-cube/#h3_dsd-dimensions), so we could set something like `codelist: false` in an object to suppress this. But the question then arises - how does a user filter on these values in PMD?
> "a component can also be optionally annotated with a qb:codeList to indicate a set of skos:Concepts which may be used as codes."

For the statistical-geography URIs, we don't have a skos hierarchy for these but one could be created. But the issue here is that this codelist would be absolutely gigantic. Do we want to create a skos hierarchy for this giant codelist to support user lookups and filtering in PMD?

@rossbowen @ajtucker any thoughts?
