### ISSUE TITLE
debugging statements/logs

### ISSUE THREAD

**Issue by mikeAdamss** [GSS-Cogs/pmd-jenkins-library#4]
doesn't necessarily have to literally be logs, but look at the pipeline components (e.g vars/uploadTidy.groovy) and liberally sprinkle around some echo/print statements and (where feasible) exception handling. The intention here is to make any issues from failed pipelines bubble up to the Jenkins console as obvious "x thing went wrong" messages.

**Comment by ajtucker** [comment]
Now that you've seen the console log from Jenkins, does this still stand?

The pmd-jenkins-pipeline tries to be sensible with the various errors that can crop up. The PMD API is quite explicit about what HTTP codes are returned, and our Groovy code will raise specific exceptions as required with details of what has gone wrong.

Where properly unexpected things happen, as in the calls to _empty_cache raising a RequestAborted exception, these will bubble up as per normal exceptions and show up in the logs.

I've tried to keep the core of the pmd-jenkins-library quite simple and just reflect the PMD API; this is the code under `src`. On top of that we've built a more Jenkins like library of (global) commands in `vars` that will generally `echo` a trace of what they're doing.

**Comment by mikeAdamss** [comment]
Cant tell tbh. I think we want things explicit and obvious but a bit too early days to have a discussion worthy view on that now tbh, it's certainly a hell of a lot less important with the convenient stack traces.

Happy to close, can always revisit at a later date if need be.
