### ISSUE TITLE
Add parameters for docker container tags

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/pmd-jenkins-library#45]
A recent glitch in building a container on hub.docker.com reminded me that it'd be a good idea to be able to pin the versions of containers used during a pipeline job.

We could pass the image name:version string to the template pipeline, e.g.:

```
familyTransformPipeline {
  databaker = 'gsscogs/databaker:1.3'
}
```

and pick this up to override the default in the pipeline template, e.g.:

```
def call(body) {
...
def FAILED_STAGE
def DATABAKER = pipelineParams['databaker'] ?: 'gsscogs/databaker'
...

agent {
  docker {
    image DATABAKER
...
```

**Comment by ajtucker** [comment]
Doing this would let us make progress on updating Python GSS-Cogs/gss-utils#95 and not worry too much about the ripple effect on databaker-docker etc.

**Comment by robons** [comment]
If we change the shared library so it's using a fixed version of each of the containers, we could use tags to keep all of the 'release' versions of the shared pipeline. Then we would just need to change the `pmd@family-pmd4` bit of the JenkinsFile in each repo the git tag we want it to use. This way we can fix only the builds we want to fix without having to do too much manual configuration.
