### ISSUE TITLE
Speed up Reference Data Pipeline

### ISSUE THREAD

**Issue by robons** [GSS-Cogs/pmd-jenkins-library#52]
Reference data is taking 20/30 minutes to build on Jenkins. It would be ideal to think of and implement an alternative approach which would allow DMs to check whether the reference data would pass tests before uploading to Jenkins.

Can we do differential uploads, or speed things up somehow? There may be some grand alternative to the current build approach would could show improvements in the time to build the reference data.

---

Rob's suggestion:

* `csv2rdf` is a clojure library (so accessible to any JVM language).
* the `sparql` command is a wrapper over the Apache Jena library (also accessible to any JVM language).

We run `csv2rdf` approximately 90 times during the trade family ref pipeline. We run `sparql` approximately 250 times during the trade family ref pipeline. Each call to these CLI utils requires the JVM to start and bytecode to be interpreted/JIT compiled - this is a lot of overhead if we're using the same code over and over again. 

Example build output: https://ci.floop.org.uk/job/GSS_data/job/Trade/job/ref_data/293/consoleText

Suggestion:

* Create a Java/Scala CLI util which allows you to run `csv2rdf` commands with one invocation of the JVM - i.e. take a JSON config file specifying input/output files for transformation. We'd only need to make one call to this CLI tool per pipeline build so safe a lot of the JVM overhead and allow suitable JIT optimisation of bytecode. 
* Create a Java/Scala CLI which can batch the calls to `sparql` together. Again, perhaps we can pass in a JSON config file which specifies which commands to run and what to do with the output. Again, we'd only need to make one call to this per pipeline with the suitable overhead saved.

--- 
@ajtucker how would you suggest approaching this? I'm not sure how we'd do a differential build without having converted the CSV-Ws to RDF and then compared them with what's already on PMD - which wouldn't save that much time since converting to RDF is where most of the time is spent in the build.
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/73846016/106888573-a6ac1380-66de-11eb-949e-c09299f1b3f0.png">

**Comment by ajtucker** [comment]
I was thinking more along the lines of GNU make, where the output is generated if it is older than the input.

**Comment by robons** [comment]
So I've done a few things:
- Bundled together many of the JVM operations like CSV2RDF & sparql updates/inserts into one process which takes a  JSON file as input configuration.
- Decreased the polling time we wait to check whether PMD has finished an upload - it could have been up to 32 seconds previously but is now 1 second.
- Bundled together all of the upload graphs into one quads file. This means there's less waiting for jobs to finish and we get performance optimisation on the PMD side since they have to run fewer jobs to index data & perform caching. 

## ref_common pipeline

### before
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/73846016/108193953-f262b200-710d-11eb-8711-6a8fab54b442.png">

### after
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/73846016/108194075-16be8e80-710e-11eb-8af9-6fa87eb6c6ac.png">

## family trade pipeline

### before
![image](https://user-images.githubusercontent.com/73846016/108194263-51c0c200-710e-11eb-9dac-8d8e546848e8.png)

### after
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/73846016/108194362-71f08100-710e-11eb-9d06-38e21af1a7ad.png">

Typically the family trade pipeline would take 20-30 mins to run, it now typically takes ~10 mins.

## Note

There is some inherent uncertainty in the time the upload process takes. This depends on the load that their drafter is currently under. But the improvements seen here are mildly encouraging.
