### ISSUE TITLE
Change Jenkins delete then upload behaviour for API Datasets

### ISSUE THREAD

**Issue by canwaf** [GSS-Cogs/pmd-jenkins-library#53]
OData datasets (`family-trade`: `HMRC_OTS`, `HMRC_RTS`) requires append behaviour instead of delete/upload when an existing dataset exists.

**Comment by canwaf** [comment]
This needs to be configurable, somewhere. OTS/RTS won't require replacement, but not all `application/json` datasets will need the same behaviour. For example, family-homelessness#1 should do a replace.

**Comment by robons** [comment]
I'm going to add some kind of boolean field into the info.json structure somewhere. If it's not there, it'll default to deleting the existing graph. If it's set and is `true` then I'll avoid deleting the graph which will (hopefully) allow the accretive approach you desire.

**Comment by robons** [comment]
@canwaf shall we close this off now as we've technically got it (basically) working.
