### ISSUE TITLE
Guard against csv2rdf silent failure

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/pmd-jenkins-library#59]
Due to the default way that the JVM reports unhandled exceptions, `csv2rdf.clj` doesn't currently indicate any errors via the return code, so our pipeline assumes that the process always succeeds.

This results in zero length Turtle files (gzipped) and attempts to upload these to PMD, sometimes resulting in hangs, sometimes resulting in strange test results, sometimes in trivially passing tests.

While we wait for https://github.com/Swirrl/csv2rdf/issues/49 to be fixed, a workaround would be to either check the `stderr` output from the call to `csv2rdf`, check the output is non-zero (complicated by the output being gzipped), fiddle with the Docker image for `csv2rdf` to provide a return code, or fork `csv2rdf.clj` and provide a PR.

**Comment by robons** [comment]
Switching to `gss-jvm-build-tools` will ensure the build fails in an appropriate way. Builds which pass on Jenkins fail (as expected) when using the `gss-local-build-tool` which routes all CSV2RDF calls through `gss-jvm-build-tools`.

**Comment by ajtucker** [comment]
We've tested a temporary fix for csv2rdf on a fork, https://github.com/GSS-Cogs/csv2rdf.clj. It doesn't break anything.
