### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/pmd-jenkins-library#77]
The pipelines currently run CSV2RDF and then run some trivial SPARQL queries against the output to determine the eventual graphs to use when uploading to PMD. This breaks when the output is large enough as the gss-jvm-build-tools parses the whole file into main memory to run the queries.

CSV2RDF itself should be able to run against arbitrarily large CSV files as it's really just a stream processor. Before now we've also tried to ensure that the output is streamed through gzip (pigz) to deal with the explosion in the filesize going from CSV to RDF.

The current pipelines also run SPARQL on the CSV2RDF output in order to determine the refperiod codes used, which again lead to out-of-memory errors for large enough RDF data files.

The graphs are used to partition datasets into chunks and also to separate out the dataset metadata from the dataset (observations & DSD). These graphs shouldn't really the concern of the (CSV-W) publisher, but we needed a way to record them as part of the transformation process to link the dataset metadata to the dataset, and so originally dropped them into a separate TriG file along with the dataset metadata which we then SPARQLed to derive the graph URIs. The TriG file is always going to be small and so easy to SPARQL.

The main issue for graph URIs is that the relationship between the metadata graph and the dataset graph(s) needs to be recorded as part of the metadata. We've previously suggested #15 that this responsibility should move to be a concern of part of the pipeline that uploads RDF to PMD.

For the graph URIs, we could:
* Output them into e.g. JSON files as part of the transform process. The SPARQL queries just output JSON anyway for later use in managing the uploads to PMD.
* Use the CSV-W metadata JSON file as just plain JSON with the expectation that these graph URIs can be easily found.
* Use the CSV-W metadata JSON file as JSON-LD and run SPARQL over that.
* Let pmd-jenkins-pipeline manage the graph URIs and put the necessary links into the metadata.
* Ignore graphs completely and let PMD manage them, coining graph URIs from the base URI of the resources/documents.

For the (refperiod) codes-used queries, we could:
* Derive them from the CSV directly, with standard unix pipes, cut, sed, sort, uniq, etc. As this is a corner-case
* Add a virtual column and use CSV2RDF to generate triples -- note that duplicate triples will not result in duplicates in PMD (unless they're in different graphs).
* Push the responsibility up to PMD.
* Derive the codes-used after the draftset has been uploaded using similar SPARQL querying against the draftset rather than loading everything into memory.

**Comment by ajtucker** [comment]
Blocks GSS-Cogs/family-towns-and-high-streets#5

**Comment by robons** [comment]
I think the temporary fix for this issue is to run the graph extraction query on the CSV-W metadata instead of the ttl output. This can quite easily be done with a python script, and could be something easily added to the [pmdtools](https://github.com/GSS-Cogs/csvwlib/tree/main/pmd) library which is being built as a part of the csvwlib project. It already does some queries on CSV-W metadata files which can be read in as they are json-ld.
